from .auth import TOKEN, User_UUID, HASURA_WSS_ENDPOINT
from .paths import BASE_DIR, LOGS, CONSTANTS, IRRIGATION_TIME_JSON
from .queries import IRRIGATION_TIME_SUBSCRIPTION
from .pins import DHT_PIN, STACK, BUZZER_PIN
